[package]
name = "fluvio-client-wasm"
version = "0.1.0"
authors = ["Sebastian Imlay <sebastian.imlay@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
wasm-bindgen-futures = {version = "0.4.23", features = ["futures-core-03-stream"] }
fluvio = { path = "../fluvio/src/client" }
console_log = { version = "0.2", features = ["color"] }
log = "0.4"
js-sys = "0.3.51"
web-sys = {version = "0.3.51" }
tokio-stream = "0.1.5"
tracing-wasm = "0.2.0"
tracing = "0.1.26"
fluvio-future = "0.3.3"
fluvio_ws_stream_wasm = "0.7.0"
async-trait = { version = "0.1.40"}


# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }


# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5" }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

# https://rustwasm.github.io/docs/book/reference/code-size.html#optimizing-builds-for-code-size
[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true

[patch.crates-io]
fluvio-future = { git = "https://github.com/infinyon/future-aio.git", branch = "master" }
#fluvio-future = { path = "../future-aio/", features = ["net"]}
